// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUS0R-OVPbNqdR1kGi1K0D-AVPBgeofgs',
    appId: '1:680998684754:web:f51113fdd84f9bf145778b',
    messagingSenderId: '680998684754',
    projectId: 'nearfund-af6a7',
    authDomain: 'nearfund-af6a7.firebaseapp.com',
    storageBucket: 'nearfund-af6a7.appspot.com',
    measurementId: 'G-GDK7MSSE24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH3S59ZjlCIcFysED64rvh6hIwCN3ifFA',
    appId: '1:680998684754:android:ac16c8d1f1430f3f45778b',
    messagingSenderId: '680998684754',
    projectId: 'nearfund-af6a7',
    storageBucket: 'nearfund-af6a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsvabYKq2DTLHG-C4tK6L2umwOivGASQE',
    appId: '1:680998684754:ios:05ae7b405cc3124445778b',
    messagingSenderId: '680998684754',
    projectId: 'nearfund-af6a7',
    storageBucket: 'nearfund-af6a7.appspot.com',
    iosClientId: '680998684754-h6nfbft39ilnn30aii31184bnbdhr9gc.apps.googleusercontent.com',
    iosBundleId: 'com.example.nearfund',
  );
}
